all: main.c sources/busca_patricia.c sources/busca_hash.c sources/file_reader.c sources/hash.c sources/menu.c sources/patricia.c sources/patricia.c 
	gcc -o programa main.c sources/busca_patricia.c sources/busca_hash.c sources/file_reader.c sources/hash.c sources/menu.c  sources/patricia.c -lm
